### ISSUE TITLE
ES 2.x support

### ISSUE THREAD

**Issue by jstoiko** [ramses-tech/ramses#101]

**Comment by vlcinsky** [comment]
Does this mean, that Ramses currently requires some 1.x version of Elasticsearch? I did not find such information in documentation.

**Comment by jstoiko** [comment]
ES 2.x should work in ramses 0.5.3 as support has been added to nefertari 0.7.0 (see https://github.com/ramses-tech/nefertari/issues/130).

I'm going to close this issue.
