### ISSUE TITLE
Relationship to items of the same schema possible?

### ISSUE THREAD

**Issue by clamor** [ramses-tech/ramses#103]
I went through the tutorials, everything went fine. Great work.

I am wondering if there is an easy way to define a relationship between items of the same schema, something like item and subitems where subitems are also type "item"? Trying this  according to the tutorial (and using Postgres) gives an ValueError:

raise ValueError('{}: {}'.format(model_name, str(ex)))
ValueError: Person: Model `Item` used in relationship is not defined

**Comment by jstoiko** [comment]
is it possible to see your RAML/json-schema files?

**Comment by clamor** [comment]
this has been resolved by 

https://github.com/oleduc/ramses/commit/00b8f4cfe3f10faaa9d3877293586d0548631652
