### ISSUE TITLE
Unavailable scaffolds: ramses_starter

### ISSUE THREAD

**Issue by CasperCLD** [ramses-tech/ramses#105]
I am not able to create a scaffold on Python 3.5, OS X 10.11.3.
When I issue the following commands:
```
$ virtualenv my_project
$ source my_project/bin/activate
$ pip install ramses
$ pcreate -s ramses_starter my_project
```
It says:
`Unavailable scaffolds: ramses_starter`

**Comment by jstoiko** [comment]
Hi @CasperCLD, I went through those steps and could not reproduce.

```
$ virtualenv -p python3 my_project
...
(my_project) $ python3 -V                      
Python 3.5.0
$ source my_project/bin/activate
(my_project) $ pip install ramses
...
(my_project) $ pcreate -s ramses_starter my_project

        Which database backend would you like to use:

        (1) for SQLAlchemy/PostgreSQL, or
        (2) for MongoEngine/MongoDB?

        [default is '1']: 
```

**Comment by CasperCLD** [comment]
Hi @jstoiko, thank you so much for your reply. I've tried the following commando's on

- Ubuntu 14.04 LTS, Python 2.7, Python 3.4.3, Python 3.5.1
- Mac OSX 10.11.3, Python 2.7, Python 3.4, Python 3.5.1

```
$ virtualenv -p python3.5 my_project
$ source my_project/bin/activate
$ python -V
Python 3.5.1
$ pip install ramses
[full log here](http://pastebin.com/qnnfkYCY)
$ pcreate -s ramses_starter my_project
Unavailable scaffolds: ramses_starter
```

**Comment by CasperCLD** [comment]
Apparently this worked:

`pip uninstall pyramid
virtualenv -p python3.4 env
.  ./env/bin/activate
pip install ramses
pcreate -s ramses_starter my_project

        Which database backend would you like to use:

        (1) for SQLAlchemy/PostgreSQL, or
        (2) for MongoEngine/MongoDB?

        [default is '1']: 1

`
