### ISSUE TITLE
Support for / How to use geography objects?

### ISSUE THREAD

**Issue by 72616e646f6d** [ramses-tech/ramses#109]
Hi,

How can I use geography objects in ramses?
There is support for it in both postgresql and elasticsearch but I does not seem to be supported in ramses.
Do you have any idea how to use geography objects in combination with ramses? Not just storing them but also using them for search for example distance to point search.

Ty!

**Comment by mloskot** [comment]
Related discussion https://github.com/ramses-tech/nefertari/issues/142

**Comment by jstoiko** [comment]
Moving the discussion [here](https://github.com/ramses-tech/nefertari/issues/142) since this is not specific to ramses.
