### ISSUE TITLE
Ondelete not nullifying fields in docs of index 

### ISSUE THREAD

**Issue by kalyankuramana** [ramses-tech/ramses#116]
reference : ramses-example

step1: 

create a user 

step2:

create a story for this user
![image](https://cloud.githubusercontent.com/assets/753138/16586014/57b41e88-42e1-11e6-9793-32fb8f887d74.png)

*look at the request

as a result the doc in mongo

![image](https://cloud.githubusercontent.com/assets/753138/16586060/8c50eef0-42e1-11e6-909a-87ab8570c4bb.png)

step2:

delete this story  delete: /stories/{id}

now , although the story is deleted , its still showing up when queried  GET: /users/{username}

![image](https://cloud.githubusercontent.com/assets/753138/16586114/d0406640-42e1-11e6-94a1-0ff5c702acf4.png)

but the doc in mongodb is updated

![image](https://cloud.githubusercontent.com/assets/753138/16586150/f1c52e72-42e1-11e6-8236-88b3f76500e3.png)

database engine: mongodb

cheers
kalyan

**Comment by kalyankuramana** [comment]
Another similar issue 

if a user has multiple stories , and i delete one of those stories , the stories field in the user doc is nullified , that is it no more exists on the doc , but still index not updated

![image](https://cloud.githubusercontent.com/assets/753138/16586459/afdb81f8-42e3-11e6-81a5-abfcce676ecc.png)


![image](https://cloud.githubusercontent.com/assets/753138/16586463/b5a8bf9c-42e3-11e6-870a-1ff36b4d3702.png)

**Comment by jstoiko** [comment]
I was able to reproduce using `nefertari-mongodb`. @kalyankuramana have you been able to reproduce using `nefertari-sqla`? Let me know if you can.

I doubt this is related to `ramses` though. This issue should be moved to the [`nefertari-mongodb` issues](https://github.com/ramses-tech/nefertari-mongodb/issues).

**Comment by kalyankuramana** [comment]
yes, the issue arises with nefertari-sqla as well
