### ISSUE TITLE
response body cannot have a array

### ISSUE THREAD

**Issue by kalyankuramana** [ramses-tech/ramses#117]
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "orderId": {
        "type": "integer"
      }
    }
  }
}

ramses not supporting these type of schemas

**Comment by jstoiko** [comment]
there is a chapter in the doc about list fieds that might be helpful: https://ramses.readthedocs.io/en/stable/fields.html#list-fields

**Comment by jstoiko** [comment]
you can try different "item_type" like in the example below:
```
(...)
"_db_settings": {
        "type": "list",
        "item_type": "dict"
    }
(...)
```
